CREATE TABLE APPOINTMENT(
     ID INTEGER NOT NULL AUTO_INCREMENT,
     DOCTOR_ID INTEGER NOT NULL, 
     FIRST_NAME varchar(256) NOT NULL,
     LAST_NAME varchar(256) NOT NULL,
     APPT_DATE DATE NOT NULL,
     APPT_TIME TIME(9) NOT NULL,
     NEW_PATIENT BOOLEAN DEFAULT FALSE,
     DELETED BOOLEAN DEFAULT FALSE,
     CREATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
     MODIFIED TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE TEST.APPOINTMENT ADD PRIMARY KEY (ID);
ALTER TABLE TEST.APPOINTMENT ADD FOREIGN KEY (DOCTOR_ID) REFERENCES DOCTOR(ID);

INSERT INTO TEST.APPOINTMENT(ID, DOCTOR_ID, FIRST_NAME, LAST_NAME, APPT_DATE, APPT_TIME, NEW_PATIENT, DELETED) VALUES (1, 2, 'Archer', 'Sterling', '2022-11-03','08:00:00', true, false);
INSERT INTO TEST.APPOINTMENT(ID, DOCTOR_ID, FIRST_NAME, LAST_NAME, APPT_DATE, APPT_TIME, NEW_PATIENT, DELETED) VALUES (2, 2, 'Figis', 'Cyril', '2022-11-03','08:30:00', false, false);
INSERT INTO TEST.APPOINTMENT(ID, DOCTOR_ID, FIRST_NAME, LAST_NAME, APPT_DATE, APPT_TIME, NEW_PATIENT, DELETED) VALUES (3, 2, 'Gilette', 'Ray', '2022-11-03','09:00:00', false, false);
INSERT INTO TEST.APPOINTMENT(ID, DOCTOR_ID, FIRST_NAME, LAST_NAME, APPT_DATE, APPT_TIME, NEW_PATIENT, DELETED) VALUES (4, 2, 'Kane', 'Lana', '2022-11-03','09:30:00', true, false);
INSERT INTO TEST.APPOINTMENT(ID, DOCTOR_ID, FIRST_NAME, LAST_NAME, APPT_DATE, APPT_TIME, NEW_PATIENT, DELETED) VALUES (5, 2, 'Poovey', 'Pam', '2022-11-03','10:00:00', true, false);
