CREATE TABLE DOCTOR(
     ID INTEGER NOT NULL AUTO_INCREMENT,
     FIRST_NAME varchar(256) NOT NULL,
     LAST_NAME varchar(256) NOT NULL,
     EMAIL varchar(256) NOT NULL,
     ACTIVE boolean DEFAULT TRUE,
     CREATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
     MODIFIED TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE TEST.DOCTOR ADD PRIMARY KEY (ID);

INSERT INTO TEST.DOCTOR(ID, FIRST_NAME, LAST_NAME, EMAIL, ACTIVE) VALUES (1, 'Hibbert', 'Julius', 'julius@notablehealth.com', true);
INSERT INTO TEST.DOCTOR(ID, FIRST_NAME, LAST_NAME, EMAIL, ACTIVE) VALUES (2, 'Algernop', 'Krieger', 'krieger@notablehealth.com', true);
INSERT INTO TEST.DOCTOR(ID, FIRST_NAME, LAST_NAME, EMAIL, ACTIVE) VALUES (3, 'Riviera', 'Nick', 'nick@notablehealth.com', true);
--JOHN ZOIDBERG john@notablehealth.com